### ISSUE TITLE
`d-1-4` :  Preprocess PIE dataset to build NER labels for Idiomify task

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/idiomify#11]
## Why?

We need to transform the dataset into NER-compatible format.

## How?

We could get use of the labels that we already have:
like these |
--- |
<img width="604" alt="image" src="https://user-images.githubusercontent.com/56193069/157603695-c76a1985-e677-47f3-ac54-d32ae243ac92.png">| 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/56193069/157603735-310581a7-fc91-4498-a791-ca693713080d.png"> |

But why do some labels include O in between B and I, like the one above? 

[someone has asked the same question, and someone came up with an answer that I was looking for](https://datascience.stackexchange.com/a/63400) I
--- | 
<img width="692" alt="image" src="https://user-images.githubusercontent.com/56193069/157604944-1fc25ba2-7b22-4aaf-85fc-9176f3d4e518.png"> | 

So it is because some words in a phrase may not be part of the entity of the phrase.

and this is the case with idiomifiable sentences| 
--- | 
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/56193069/157606165-5254a066-39a7-4880-9d0b-d44746d34b85.png"> | 

It should not be:
- '(watched', 'B'), ('the', 'I'), ('workers', 'I'), ('at', 'I'), ('his', 'I'), ('office', 'I'), ('carefully', 'I')`

because it is only `watched` & and `carefully` that corresponds to the meaning of `keep an eye on` in isolation.

## To-do's
- [x] we don't need `annotate` anymore
- [x] `explore_fetch_pie_replace_labels.py`
- [x] change `main_upload_literal2idiomatic` to preprocess the labels

**Comment by eubinecto** [comment]
## Should I change the name of the artifact?

Yes, I think you should. `literal2idiomatic` is rather misleading.
