### ISSUE TITLE
Implement `Idiomifier`class with OpenAI's GPT-3 API

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/idiomify#16]
## To-do's
- [x] how do I programmatically interact with Open AI's GPT-3? 
- [x] register your API key as an environment variable for the project in Pycharm 
- [x] `explore_openai_completion.py` 
- [x] `run_deploy.py`

**Comment by eubinecto** [comment]
OpenAI has a guide on using their API with Python:
https://beta.openai.com/docs/libraries/python-bindings

**Comment by eubinecto** [comment]
## Some examples

<img width="754" alt="image" src="https://user-images.githubusercontent.com/56193069/162627955-a160ae59-b234-4f9c-a1a0-21a6f7f09bc1.png">

<img width="774" alt="image" src="https://user-images.githubusercontent.com/56193069/162628064-16ad8385-fc2f-4fa5-bde9-d7acd506e53f.png">

**Comment by eubinecto** [comment]
## More examples 

<img width="758" alt="image" src="https://user-images.githubusercontent.com/56193069/162630020-1e2563f3-f0cb-4460-83d0-9de4e4c0c6dc.png">
