### ISSUE TITLE
Implementing `m-1-2` -  testset, metrics, deploy

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/idiomify#2]
## What?
Train Seq2Seq on the whole dataset.
Submit a random paragraph, and let Idiomifer idiomify the whole paragraph. See what we get from this.

## Why? 

We want to have a taste of what Idiomifer as a rewriter could be able to do. After you see the results on a random paragraph,
you may be able to have a sense of what should be the direction of my dissertation.
 

## To-do's
- [x] 데이터셋 - train / test split 하기 (wisdomify 코드의 도움을 받으면 될 것)
- [x] datamodule을 변경하기 (이전의 모델을 굳이 지원할 필요는 없다. 그냥 변경하자!) 
- [x] pipeline  - 배치 프로세싱
- [ ] paragraph를 처리할 수 있는 상태에서 git tag -a tag012 할 것!

**Comment by eubinecto** [comment]
## train / test split 하기

이거 코드가 어디에 있더라..?

**Comment by eubinecto** [comment]
## Paragraph 처리? 

Streamlit을 꺼내들을때가.. 오고야만 것인가..

**Comment by eubinecto** [comment]
## Deployed to streamlit

https://share.streamlit.io/eubinecto/idiomify/issue_2/main_deploy.py

한가지 ... wandb login이 필요없을 줄 알았는데 ,갑자기 로그인이 필요하다고 하더라.
하지만 다행스럽게도 streamlit에서 secrets 환경변수 설정을 지원한다.
그래서 거기에다가 WANDB_API_KEY를 집어넣으니 잘만된다! 예이!
